require('dotenv').config({
  path: require('path').join(__dirname, '../../.env'),
});
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const User = require('../models/User');
const Product = require('../models/Product');
const Order = require('../models/Order');
const Review = require('../models/Review');
const connectDB = require('../config/db');

const seed = async () => {
  await connectDB();
  console.log('Seeding database...');

  await User.deleteMany({});
  await Product.deleteMany({});
  await Order.deleteMany({});
  await Review.deleteMany({});

  const salt = await bcrypt.genSalt(10);

  const users = await User.insertMany([
    {
      name: 'Ramesh Kumar',
      email: 'farmer@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543210',
      role: 'farmer',
      address: 'Village Rampur',
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      coordinates: { lat: 19.9975, lng: 73.7898 },
    },
    {
      name: 'Priya Sharma',
      email: 'consumer@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543211',
      role: 'consumer',
      address: '12 Gandhi Nagar',
      pincode: '400002',
      city: 'Mumbai',
      state: 'Maharashtra',
      coordinates: { lat: 19.076, lng: 72.877 },
    },
    {
      name: 'Suresh Patel',
      email: 'delivery@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543212',
      role: 'delivery',
      address: 'Near Bus Stand',
      pincode: '400003',
      city: 'Pune',
      state: 'Maharashtra',
      coordinates: { lat: 18.5204, lng: 73.8567 },
    },
    {
      name: 'KrishiSetu Admin',
      email: 'rammilanlodhi822@gmail.com',
      password: await bcrypt.hash('7748873679', salt),
      phone: '9876543213',
      role: 'admin',
      address: 'KrishiSetu HQ',
      pincode: '400004',
      city: 'Mumbai',
      state: 'Maharashtra',
      coordinates: { lat: 19.076, lng: 72.877 },
    },
    {
      name: 'Vikram Singh',
      email: 'vikram@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543214',
      role: 'farmer',
      address: 'Village Khatauli',
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      coordinates: { lat: 29.2755, lng: 77.7086 },
    },
    {
      name: 'Anita Reddy',
      email: 'anita@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543215',
      role: 'farmer',
      address: 'Kolar Farm',
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      coordinates: { lat: 13.1367, lng: 78.1297 },
    },
    {
      name: 'Mohan Lal',
      email: 'mohan@gmail.com',
      password: await bcrypt.hash('123456', salt),
      phone: '9876543216',
      role: 'farmer',
      address: 'Amritsar Village',
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      coordinates: { lat: 31.634, lng: 74.8723 },
    },
  ]);

  const [farmer, consumer, delivery, admin, farmer2, farmer3, farmer4] = users;

  const products = await Product.insertMany([
    // VEGETABLES

    {
      name: 'Tomato',
      category: 'Vegetables',
      quantity: 200,
      unit: 'kg',
      price: 28,
      description:
        'Fresh red tomatoes directly from our farm. No pesticides, hand-picked daily.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 40,
      suggestedPrice: 28,
      demandLevel: 'High',
      rating: 4.5,
      totalReviews: 8,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 450,
      image:
        'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Potato',
      category: 'Vegetables',
      quantity: 500,
      unit: 'kg',
      price: 18,
      description:
        'Premium quality potatoes. Large and fresh, directly from the farm.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 28,
      suggestedPrice: 18,
      demandLevel: 'High',
      rating: 4.2,
      totalReviews: 12,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Stable',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 820,
      image:
        'https://images.unsplash.com/photo-1518977676601-b53f82aba655?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Onion',
      category: 'Vegetables',
      quantity: 300,
      unit: 'kg',
      price: 32,
      description: "Nashik's famous onions. Strong flavor, long shelf life.",
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 45,
      suggestedPrice: 32,
      demandLevel: 'High',
      rating: 4.7,
      totalReviews: 15,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 680,
      image:
        'https://images.unsplash.com/photo-1508747703725-719777637510?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Carrot',
      category: 'Vegetables',
      quantity: 120,
      unit: 'kg',
      price: 22,
      description:
        'Crispy, sweet carrots. Rich in beta-carotene. Farm-fresh daily.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 35,
      suggestedPrice: 22,
      demandLevel: 'Medium',
      rating: 4.3,
      totalReviews: 7,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Stable',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 310,
      image:
        'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Cabbage',
      category: 'Vegetables',
      quantity: 80,
      unit: 'kg',
      price: 18,
      description:
        'Fresh green cabbage. Crisp and tender. Ideal for salads and cooking.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 28,
      suggestedPrice: 18,
      demandLevel: 'Medium',
      rating: 4.0,
      totalReviews: 5,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Stable',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 180,
      image:
        'https://images.unsplash.com/photo-1611105637889-3afd7295bdbf?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Cauliflower',
      category: 'Vegetables',
      quantity: 100,
      unit: 'kg',
      price: 25,
      description: 'White and firm cauliflower heads. Freshly harvested.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 38,
      suggestedPrice: 25,
      demandLevel: 'Medium',
      rating: 4.1,
      totalReviews: 6,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 220,
      image:
        'https://images.unsplash.com/photo-1510627498534-cf7e9002facc?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Garlic',
      category: 'Vegetables',
      quantity: 60,
      unit: 'kg',
      price: 75,
      description: 'Pungent desi garlic. Strong aroma, medicinal properties.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 110,
      suggestedPrice: 75,
      demandLevel: 'High',
      rating: 4.6,
      totalReviews: 11,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Rising',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 145,
      image:
        'https://thumbs.dreamstime.com/b/ai-generator-image-farmer-happily-picking-garlic-field-garlic-countryside-farm-good-weather-ai-generator-image-350431056.jpg',
    },

    {
      name: 'Ginger',
      category: 'Vegetables',
      quantity: 50,
      unit: 'kg',
      price: 65,
      description:
        'Fresh raw ginger. Spicy and aromatic. Perfect for chai and cooking.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 90,
      suggestedPrice: 65,
      demandLevel: 'Medium',
      rating: 4.4,
      totalReviews: 8,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 115,
      image:
        'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Green Chilli',
      category: 'Vegetables',
      quantity: 40,
      unit: 'kg',
      price: 45,
      description:
        'Spicy green chillies. Fresh from the farm. No artificial ripening.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 65,
      suggestedPrice: 45,
      demandLevel: 'High',
      rating: 4.3,
      totalReviews: 9,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Rising',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 260,
      image:
        'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Spinach',
      category: 'Vegetables',
      quantity: 60,
      unit: 'kg',
      price: 20,
      description:
        'Tender green spinach leaves. Rich in iron. Freshly harvested morning daily.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 30,
      suggestedPrice: 20,
      demandLevel: 'Medium',
      rating: 4.2,
      totalReviews: 7,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Stable',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 190,
      image:
        'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Mango',
      category: 'Fruits',
      quantity: 150,
      unit: 'kg',
      price: 65,
      description: 'Alphonso mangoes. Sweet, pulpy and aromatic.',
      farmerId: farmer2._id,
      farmerName: farmer2.name,
      farmerLocation: 'Muzaffarnagar, UP',
      mandiPrice: 100,
      suggestedPrice: 65,
      demandLevel: 'High',
      rating: 4.9,
      totalReviews: 20,
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      marketTrend: 'Rising',
      coordinates: { lat: 29.2755, lng: 77.7086 },
      totalSold: 310,
      image:
        'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Banana',
      category: 'Fruits',
      quantity: 200,
      unit: 'dozen',
      price: 35,
      description:
        'Yellow ripe Robusta bananas. Naturally ripened, no chemicals.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 55,
      suggestedPrice: 35,
      demandLevel: 'High',
      rating: 4.4,
      totalReviews: 13,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Stable',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 540,
      image:
        'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=1200&auto=format&fit=crop',
    },
    {
      name: 'Apple',
      category: 'Fruits',
      quantity: 100,
      unit: 'kg',
      price: 85,
      description: 'Kashmiri red apples. Crisp, juicy and naturally sweet.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 130,
      suggestedPrice: 85,
      demandLevel: 'High',
      rating: 4.7,
      totalReviews: 16,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 280,
      image:
        'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Papaya',
      category: 'Fruits',
      quantity: 80,
      unit: 'kg',
      price: 28,
      description:
        'Ripe sweet papaya. Rich in vitamin C and digestive enzymes.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 45,
      suggestedPrice: 28,
      demandLevel: 'Medium',
      rating: 4.2,
      totalReviews: 8,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Stable',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 175,
      image:
        'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Orange',
      category: 'Fruits',
      quantity: 120,
      unit: 'kg',
      price: 55,
      description: 'Nagpur oranges. Juicy, tangy and vitamin-rich.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 80,
      suggestedPrice: 55,
      demandLevel: 'High',
      rating: 4.6,
      totalReviews: 14,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 340,
      image:
        'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Grapes',
      category: 'Fruits',
      quantity: 60,
      unit: 'kg',
      price: 72,
      description: 'Nashik seedless grapes. Sweet and juicy.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 110,
      suggestedPrice: 72,
      demandLevel: 'High',
      rating: 4.8,
      totalReviews: 18,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 195,
      image:
        'https://images.unsplash.com/photo-1515778767554-6d4fdf9f7343?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Watermelon',
      category: 'Fruits',
      quantity: 200,
      unit: 'kg',
      price: 18,
      description:
        'Large sweet watermelons. Hydrating and refreshing summer fruit.',
      farmerId: farmer2._id,
      farmerName: farmer2.name,
      farmerLocation: 'Muzaffarnagar, UP',
      mandiPrice: 28,
      suggestedPrice: 18,
      demandLevel: 'High',
      rating: 4.3,
      totalReviews: 10,
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      marketTrend: 'Stable',
      coordinates: { lat: 29.2755, lng: 77.7086 },
      totalSold: 420,
      image:
        'https://images.stockcake.com/public/1/8/b/18bc662b-17b0-45e9-a39f-7602d72985de_large/watermelon-field-harvest-stockcake.jpg',
    },

    {
      name: 'Pomegranate',
      category: 'Fruits',
      quantity: 80,
      unit: 'kg',
      price: 90,
      description: 'Ruby red pomegranates. Rich in antioxidants.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 140,
      suggestedPrice: 90,
      demandLevel: 'Medium',
      rating: 4.7,
      totalReviews: 12,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Rising',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 155,
      image:
        'https://images.unsplash.com/photo-1541344999736-83eca272f6fc?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Wheat',
      category: 'Grains',
      quantity: 1000,
      unit: 'kg',
      price: 22,
      description:
        'Punjab sharbati wheat. Premium variety ideal for chapati flour.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 32,
      suggestedPrice: 22,
      demandLevel: 'High',
      rating: 4.5,
      totalReviews: 9,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 2100,
      image:
        'https://images.unsplash.com/photo-1501430654243-c934cec2e1c0?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Rice',
      category: 'Grains',
      quantity: 800,
      unit: 'kg',
      price: 42,
      description: 'Long-grain Basmati rice. Aromatic, fluffy when cooked.',
      farmerId: farmer2._id,
      farmerName: farmer2.name,
      farmerLocation: 'Muzaffarnagar, UP',
      mandiPrice: 62,
      suggestedPrice: 42,
      demandLevel: 'High',
      rating: 4.6,
      totalReviews: 18,
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      marketTrend: 'Stable',
      coordinates: { lat: 29.2755, lng: 77.7086 },
      totalSold: 1560,
      image:
        'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Corn',
      category: 'Grains',
      quantity: 300,
      unit: 'kg',
      price: 20,
      description: 'Fresh yellow corn. Good for roasting, salads and curries.',
      farmerId: farmer2._id,
      farmerName: farmer2.name,
      farmerLocation: 'Muzaffarnagar, UP',
      mandiPrice: 30,
      suggestedPrice: 20,
      demandLevel: 'Medium',
      rating: 4.1,
      totalReviews: 5,
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      marketTrend: 'Stable',
      coordinates: { lat: 29.2755, lng: 77.7086 },
      totalSold: 390,
      image:
        'https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Bajra',
      category: 'Grains',
      quantity: 500,
      unit: 'kg',
      price: 25,
      description: 'Pearl millet from Rajasthan. Nutritious and gluten-free.',
      farmerId: farmer2._id,
      farmerName: farmer2.name,
      farmerLocation: 'Muzaffarnagar, UP',
      mandiPrice: 38,
      suggestedPrice: 25,
      demandLevel: 'Medium',
      rating: 4.0,
      totalReviews: 4,
      pincode: '251201',
      city: 'Muzaffarnagar',
      state: 'Uttar Pradesh',
      marketTrend: 'Stable',
      coordinates: { lat: 29.2755, lng: 77.7086 },
      totalSold: 620,
      image:
        'https://images.unsplash.com/photo-1603048719539-9ecb4f7d0f16?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Masoor Dal',
      category: 'Grains',
      quantity: 200,
      unit: 'kg',
      price: 78,
      description: 'Red lentils (masoor dal). High in protein, easy to cook.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 115,
      suggestedPrice: 78,
      demandLevel: 'High',
      rating: 4.4,
      totalReviews: 11,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Rising',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 340,
      image:
        'https://images.unsplash.com/photo-1612257999756-2e7395f5b72f?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Milk (A2)',
      category: 'Dairy',
      quantity: 100,
      unit: 'litre',
      price: 52,
      description: 'Pure A2 cow milk. Delivered fresh every morning.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 72,
      suggestedPrice: 52,
      demandLevel: 'High',
      rating: 4.8,
      totalReviews: 25,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Stable',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 940,
      image:
        'https://images.unsplash.com/photo-1550583724-b2692b85b150?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Paneer',
      category: 'Dairy',
      quantity: 50,
      unit: 'kg',
      price: 220,
      description: 'Fresh homemade paneer. Soft, crumbly texture. Made daily.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 320,
      suggestedPrice: 220,
      demandLevel: 'High',
      rating: 4.7,
      totalReviews: 17,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 210,
      image:
        'https://static.toiimg.com/thumb/126673696.jpg?imgsize=1028540&photoid=126673696&width=600&height=335&resizemode=75',
    },

    {
      name: 'Curd',
      category: 'Dairy',
      quantity: 80,
      unit: 'kg',
      price: 55,
      description:
        'Thick probiotic curd. Made from fresh cow milk. No preservatives.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 75,
      suggestedPrice: 55,
      demandLevel: 'High',
      rating: 4.5,
      totalReviews: 14,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Stable',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 460,
      image:
        'https://media.istockphoto.com/id/979356494/photo/ricotta-cheese-cottage-cheese-farmers-cheese-curd-or-tvorog-in-a-wooden-bowl.jpg?s=612x612&w=0&k=20&c=1wYRUpZf6er8gDSoOlK7yLDYMyzmjO0OLhsBZjxFspM=',
    },

    {
      name: 'Butter',
      category: 'Dairy',
      quantity: 30,
      unit: 'kg',
      price: 420,
      description:
        'Pure white butter (makhan). Made from fresh cream. Rich and nutritious.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 580,
      suggestedPrice: 420,
      demandLevel: 'Medium',
      rating: 4.6,
      totalReviews: 9,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 85,
      image:
        'https://thumbs.dreamstime.com/b/female-farmer-holding-jar-clarified-butter-ghee-honey-against-background-cows-grazing-meadow-418864443.jpg?w=992',
    },

    {
      name: 'Organic Spinach',
      category: 'Organic',
      quantity: 80,
      unit: 'kg',
      price: 35,
      description:
        '100% organic spinach. No chemicals, no pesticides. Certified organic.',
      farmerId: farmer._id,
      farmerName: farmer.name,
      farmerLocation: 'Nashik, Maharashtra',
      mandiPrice: 50,
      suggestedPrice: 35,
      demandLevel: 'Medium',
      rating: 4.4,
      totalReviews: 9,
      pincode: '400001',
      city: 'Nashik',
      state: 'Maharashtra',
      marketTrend: 'Stable',
      coordinates: { lat: 19.9975, lng: 73.7898 },
      totalSold: 220,
      image:
        'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Organic Honey',
      category: 'Organic',
      quantity: 40,
      unit: 'kg',
      price: 350,
      description:
        'Pure raw forest honey. Unprocessed, no sugar added. Rich in antioxidants.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 500,
      suggestedPrice: 350,
      demandLevel: 'High',
      rating: 4.9,
      totalReviews: 22,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Rising',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 130,
      image:
        'https://images.unsplash.com/photo-1587049352851-8d4e89133924?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Organic Wheat Flour',
      category: 'Organic',
      quantity: 200,
      unit: 'kg',
      price: 45,
      description:
        'Stone-ground whole wheat flour. 100% organic. High fibre, no maida.',
      farmerId: farmer4._id,
      farmerName: farmer4.name,
      farmerLocation: 'Amritsar, Punjab',
      mandiPrice: 65,
      suggestedPrice: 45,
      demandLevel: 'Medium',
      rating: 4.5,
      totalReviews: 11,
      pincode: '143001',
      city: 'Amritsar',
      state: 'Punjab',
      marketTrend: 'Stable',
      coordinates: { lat: 31.634, lng: 74.8723 },
      totalSold: 380,
      image:
        'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1200&auto=format&fit=crop',
    },

    {
      name: 'Organic Veggie Pack',
      category: 'Organic',
      quantity: 60,
      unit: 'kg',
      price: 120,
      description:
        'Mixed organic vegetables pack — tomato, carrot, beans, spinach. Weekly box.',
      farmerId: farmer3._id,
      farmerName: farmer3.name,
      farmerLocation: 'Kolar, Karnataka',
      mandiPrice: 180,
      suggestedPrice: 120,
      demandLevel: 'High',
      rating: 4.6,
      totalReviews: 15,
      pincode: '563101',
      city: 'Kolar',
      state: 'Karnataka',
      marketTrend: 'Rising',
      coordinates: { lat: 13.1367, lng: 78.1297 },
      totalSold: 95,
      image:
        'https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=1200&auto=format&fit=crop',
    },
  ]);

  const order = await Order.create({
    customer: consumer._id,
    farmer: farmer._id,
    deliveryPartner: delivery._id,
    products: [
      {
        product: products[0]._id,
        name: 'Tomato',
        price: 28,
        quantity: 5,
        image: '',
      },
    ],
    totalAmount: 170,
    deliveryFee: 30,
    platformFee: 7,
    farmerAmount: 133,
    partnerEarning: 20,
    deliveryAddress: {
      address: '12 Gandhi Nagar',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400002',
    },
    paymentStatus: 'Escrow Hold',
    deliveryStatus: 'Out for Delivery',
    paymentMethod: 'stripe',
    farmerPaymentReleased: false,
    trackingUpdates: [
      {
        status: 'Pending',
        note: 'Order placed',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        status: 'Assigned',
        note: 'Delivery partner assigned',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        status: 'Picked Up',
        note: 'Package picked up from farmer',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
      {
        status: 'Out for Delivery',
        note: 'On the way to your location',
        timestamp: new Date(),
      },
    ],
  });

  await Review.create([
    {
      user: consumer._id,
      product: products[0]._id,
      farmer: farmer._id,
      order: order._id,
      rating: 5,
      comment: 'Excellent tomatoes! Very fresh and juicy. Will order again.',
      userName: consumer.name,
    },
    {
      user: consumer._id,
      product: products[1]._id,
      farmer: farmer._id,
      rating: 4,
      comment: 'Good quality potatoes. Fresh from farm.',
      userName: consumer.name,
    },
    {
      user: consumer._id,
      product: products[10]._id,
      farmer: farmer2._id,
      rating: 5,
      comment: 'Best mangoes I have ever tasted! So sweet and fresh.',
      userName: consumer.name,
    },
  ]);

  console.log('\n✅ Database seeded successfully!');
  console.log(`✅ ${products.length} products seeded across all categories`);
  console.log('✅ Admin: rammilanlodhi822@gmail.com');
  process.exit(0);
};

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
